Add post testing fixes

diff --git a/port-forward b/port-forward
--- a/port-forward
+++ b/port-forward
@@ -10,14 +10,16 @@ PHASE=$2
 BRIDGE=""
 HOSTADDR=""
 
+echo "$PHASE"
+
 # Exit if not relevant phase
-if [[ $PHASE != "post-start" && "$PHASE" == "pre-stop" ]]; then
+if [[ $PHASE != "pre-start" && $PHASE != "post-start" && "$PHASE" != "pre-stop" ]]; then
 	exit
 fi
 
 service_exists() {
 	# Expects param 1 to be the service name
-	if [[ systemctl list-unit-files "$1.service" >/dev/null ]]; then
+	if systemctl list-unit-files "$1.service" >/dev/null; then
 		return 0
 	else
 		return 1
@@ -26,24 +28,25 @@ service_exists() {
 
 mod_iptables() {
 	#Adds or removes iptables rules - paramters are action and rule. Use 'add' to add rule, anything else to remove it. Recommend 'remov' or 'delet' for logging purposes
-	if [[ "$1"=="add" ]]; then
+	if [[ "$1" == "add" ]]; then
 		ACTION="-A"
 	else
 		ACTION="-D"
 	fi
-	iptables -t nat $MODE PREROUTING $2 && echo "iptables rule $2 $1ed" || echo "Error $1ing rule $2"
+	iptables -t nat $ACTION PREROUTING $2 && echo "iptables rule '$2' $1ed" || echo "Error $1ing rule '$2'"
 }
 
 add_forward() {
-	FWFM=$1
-	FWPR=$2
-	FWSRC=$3
-	FWTO=$4
-	FWPORT=$5
+	FWORIGADDR=$1
+	FWPROTO=$2
+	FWORIGPORT=$3
+	FWTOADDR=$4
+	FWTOPORT=${5:-$FWORIGPORT}
 
-	if [[ service_exists socat-forwarder ]]; then
+	if service_exists "socat-forwarder-$FWPROTO@"; then
 		# Start a systemd service to forward the ports with socat
-		systemctl start "socat-forwarder-$FWPROTO@$FWORIGPORT-$FWTOADDR:$FWTOPORT"
+		FWDR="$FWPROTO@$FWORIGPORT-$FWTOADDR:$FWTOPORT"
+		systemctl start "socat-forwarder-$FWDR" && echo "Started socat forwarder $FWDR" || echo "Error starting socat forwarder $FWDR"
 	else
 		# Use iptables rules to forward the port
 		mod_iptables "add" "-p $FWPROTO -d $FWORIGADDR -m $FWPROTO --dport $FWORIGPORT -j DNAT --to-destination $FWTOADDR:$FWTOPORT"
@@ -55,11 +58,12 @@ remove_forward() {
 	FWPROTO=$2
 	FWORIGPORT=$3
 	FWTOADDR=$4
-	FWTOPORT=${5:-4}
+	FWTOPORT=${5:-$FWORIGPORT}
 
-	if [[ service_exists "socat-forwarder-$FWPROTO" ]]; then
+	if service_exists "socat-forwarder-$FWPROTO@"; then
 		# Stop a systemd service to forward the ports with socat
-		systemctl stop "socat-forwarder-$FWPROTO@$FWORIGPORT-$FWTOADDR:$FWTOPORT"
+		FWDR="$FWPROTO@$FWORIGPORT-$FWTOADDR:$FWTOPORT"
+		systemctl stop "socat-forwarder-$FWDR" || echo "Error stopping socat forwarder $FWDR"
 	else
 		# Use iptables rules to forward the port
 		mod_iptables "remov" "-p $FWPROTO -d $FWORIGADDR -m $FWPROTO --dport $FWORIGPORT -j DNAT --to-destination $FWTOADDR:$FWTOPORT"
@@ -76,19 +80,26 @@ if [[ -z "$HOSTADDR" ]]; then
 fi
 
 # Get configuration information for machine
-DESC=$($(qm config $VMID 2>/dev/null || pct config $VMID) | grep "^description" | sed 's/^.*: //')
-# Find the first IP address statically configured in config
-ADDRESS=$($(qm config $VMID 2>/dev/null || pct config $VMID) | grep "^net" | sed 's/^.*: //' | grep -Po '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b' | head -n 1)
+if qm conf $VMID >/dev/null 2>&1; then
+	FWDDATA=$(qm config $VMID | grep "^description" | sed -E 's/^.*: //;s/^.*port-forwards(%3A)?%0A//I;s/%0A%0A.*$//Ig;s/%3A/:/g;s/%0A/\n/g')
+	# Find the first IP address configured in cloud-init settings
+	ADDRESS="$(qm config $VMID 2>/dev/null | grep "^ipconfig" | sed 's/^.*: //' | grep -Po '(?<=ip=)\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b' | head -n 1)"
+else
+	FWDDATA=$(pct config $VMID | grep "^description" | sed -E 's/^.*: //;s/^.*port-forwards(%3A)?%0A//I;s/%0A%0A.*$//Ig;s/%3A/:/g;s/%0A/\n/g')
+	# Find the first IP address statically configured in config
+	ADDRESS=$(pct config $VMID | grep "^net" | sed 's/^.*: //' | grep -Po '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b' | head -n 1)
+fi
 
 echo "Port forward script running $PHASE for $VMID and detected parameters as Host: $HOSTADDR, Bridge: $BRIDGE, VM Addr: $ADDRESS"
 # Extract port forwarding configuration from description
 # Extracts data lines from a line ending with "port-forwards:" to a double new line and converts encoded symbols
-FWDDATA=$(echo "$DESC" | sed 's/^.*port-forwards(?:%3A)?%0A//I;s/%0A%0A.*$//Ig;s/;s/%3A/:/g;s/%0A/\n/g')
 
 # If no data was found, exit the hook
 if [[ -z "$FWDDATA" ]]; then
 	exit
 fi
+
+echo "Processing port forwarding"
 
 PROTO="tcp"
 echo "$FWDDATA" | while read linedata
@@ -98,15 +109,21 @@ do
 		# Extract an IPv4 address - use this as destination until updated
 		ADDRESS=$(echo "$linedata" | grep -Po '\b\d{1,3}\.\d{1.3}\.\d{1.3}\.\d{1.3}\b')
 	# Look for protocol type in line - use this as the protocol until changed
-	elif [[ "$lineaddr" =~ "tcp" ]]; then
+	elif [[ "$linedata" =~ "tcp" ]]; then
 		PROTO="tcp"
-	elif [[ "$lineaddr" =~ "udp" ]]; then
+	elif [[ "$linedata" =~ "udp" ]]; then
 		PROTO="udp"
-	elif [[ "$lineaddr" =~ ^[^0-9]*[0-9]{1,5}[^0-9]+[0-9]{1,5}[^0-9]*$ ]]; then
+	elif [[ "$linedata" =~ ^[^0-9]*[0-9]{1,5}[^0-9]+[0-9]{1,5}[^0-9]*$ ]]; then
 		# Line contains two 1-5 digit numbers separated by non-digits
-		SPORT=$(echo "$linedata" | sed -E 's/^*[0-9]*([0-9]+)[^0-9]+([0-9]+)[0-9]*$/\1/')
-		DPORT=$(echo "$linedata" | sed -E 's/^*[0-9]*([0-9]+)[^0-9]+([0-9]+)[0-9]*$/\2/')
-		if [[ "$PHASE" == "post-start" ]]; then
+		SPORT=$(echo "$linedata" | sed -E 's/^[^0-9]*([0-9]+)[^0-9]+([0-9]+)[^0-9]*$/\1/')
+		DPORT=$(echo "$linedata" | sed -E 's/^[^0-9]*([0-9]+)[^0-9]+([0-9]+)[^0-9]*$/\2/')
+		# Exit if no static address configuration. TODO - Handle dynamic addresses through QEMU guest agent or lxc-info
+		if [[ "$PHASE" == "pre-start" ]]; then
+			if [[ -z "$ADDRESS" ]]; then
+				echo "Address not found in configuration or description. Use an address line to force this."
+				exit 126
+			fi
+		elif [[ "$PHASE" == "post-start" ]]; then
 			add_forward $HOSTADDR $PROTO $SPORT $ADDRESS $DPORT
 		elif [[ "$PHASE" == "pre-stop" ]]; then
 			remove_forward $HOSTADDR $PROTO $SPORT $ADDRESS $DPORT
